In [1]:
import numpy as np
np.random.random((2,3))

array([[0.04966445, 0.09282318, 0.40838041],
       [0.95351164, 0.65136396, 0.97970822]])

In [2]:
import numpy as np

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.full((3,4),10.11)

array([[10.11, 10.11, 10.11, 10.11],
       [10.11, 10.11, 10.11, 10.11],
       [10.11, 10.11, 10.11, 10.11]])

In [6]:
def square(n):
    return n**2
square(5)

25

In [7]:
sq = lambda n : n**2

In [8]:
sq(4)

16

In [9]:
def sum1(a,b):
    return a+b
sum1(2,3)

5

In [10]:
summ=lambda a,b:a+b

In [11]:
summ(3,4)

7

In [12]:
type(summ)

function

In [13]:
type(sum1)

function

In [16]:
sum2=lambda a,b,c: (a+b)*c

In [17]:
sum2(2,3,4)

20

In [8]:
a = eval(input("Give me all the numbers: "))

Give me all the numbers: 1,2,3,4,5


In [5]:
b = list(map(int,input().split()))

1 2 3 4 5


In [9]:
a

(1, 2, 3, 4, 5)

In [6]:
b

[1, 2, 3, 4, 5]

In [36]:
list1 = [1,2,3,4]
list2= []
for i in list1:
    list2.append(i**2)
list2

[1, 4, 9, 16]

In [75]:
list1 = [1,2,3,4,5,6]
list2=[]


for i in list1:
    if i%2 == 0:
        list2.append(i*2)

    else:
        list2.append(i**2)

            
        
        

In [76]:
list2

[1, 4, 9, 8, 25, 12]

# 1 Dimentional array

In [77]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

# 2- Dimentional Array

In [78]:
b = np.array([[1,2,3],[2,3,4]])

In [79]:
b

array([[1, 2, 3],
       [2, 3, 4]])

# Initialize all the elements of x X y array

In [80]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# Arrange the numbers between x and y with an interval of z

In [85]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [2]:
import numpy as np


np.arange(10,20,2)

array([10, 12, 14, 16, 18])

# Arrange "z" numbers between x and y

In [3]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [4]:
np.linspace(2,5,5)

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [7]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

# Filling same number in an array of dimention x X y

In [9]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [10]:
np.full((3,4),1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# Filling random number in an array of dimention x X y 

In [13]:
np.random.random((2,3))

array([[0.31910655, 0.35835483, 0.85116921],
       [0.31498523, 0.90690075, 0.75949556]])

In [15]:
np.random.random((3,4))

array([[0.02300823, 0.91584031, 0.32481049, 0.88560624],
       [0.47747937, 0.16741686, 0.01259402, 0.06431068],
       [0.28419144, 0.27905119, 0.64593126, 0.51547997]])

# Inspecting the array: Checking the size of the array

In [16]:
a = np.array([[0.02300823, 0.91584031, 0.32481049, 0.88560624],
       [0.47747937, 0.16741686, 0.01259402, 0.06431068],
       [0.28419144, 0.27905119, 0.64593126, 0.51547997]])
print(a.size)

12


In [17]:
a.shape

(3, 4)

# Inspecting the array: Resize the array

In [18]:
a = np.array([[2,3,4],[3,4,5]])
a.shape = (3,2)

In [19]:
a

array([[2, 3],
       [4, 3],
       [4, 5]])

In [20]:
b = np.array([[0.02300823, 0.91584031, 0.32481049, 0.88560624],
       [0.47747937, 0.16741686, 0.01259402, 0.06431068],
       [0.28419144, 0.27905119, 0.64593126, 0.51547997]])
b.shape = (6,2)

In [21]:
b

array([[0.02300823, 0.91584031],
       [0.32481049, 0.88560624],
       [0.47747937, 0.16741686],
       [0.01259402, 0.06431068],
       [0.28419144, 0.27905119],
       [0.64593126, 0.51547997]])