In [3]:
n = input()

2


In [4]:
type(n)

str

In [9]:
n = int(input())

4


In [10]:
type(n)

int

In [11]:
m = eval(input("Give me all the number "))

Give me all the number 1,2,3,4,5


In [12]:
m

(1, 2, 3, 4, 5)

In [13]:
m = list(map(int,input().split()))

1 2 3 4 5


In [14]:
m

[1, 2, 3, 4, 5]

In [15]:
n = [1,2,3,4]
p = []
for i in n:
    p.append(i*2)
p

[2, 4, 6, 8]

In [16]:
import numpy as np

s = np.random.random((2,3))

In [17]:
s

array([[0.80935857, 0.57931068, 0.74022753],
       [0.30697138, 0.38222026, 0.90096493]])

In [18]:
s.shape

(2, 3)

In [19]:
s.size

6

In [20]:
s.shape = (3,2)

In [21]:
s

array([[0.80935857, 0.57931068],
       [0.74022753, 0.30697138],
       [0.38222026, 0.90096493]])

In [22]:
s.size

6

In [34]:
np.random.randint(1,5)

3

In [56]:
np.full((4,4),np.random.randint(0,10))

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [60]:
np.random.randint(1,15,size = (5,4),dtype='l')

array([[ 8,  9,  6,  8],
       [ 5, 12,  3,  1],
       [ 7, 10,  7, 10],
       [ 1, 10, 14,  9],
       [ 8, 13,  3,  2]])

# Addition

In [62]:
import numpy as np

np.sum([[1,2],[3,5]],axis = 0)

array([4, 7])

In [63]:
np.sum([[1,2],[3,5]],axis = 1)

array([3, 8])

In [64]:
np.sum([[1,2],[3,5]])

11

 # subtraction

In [65]:
np.subtract(10,5)

5